# use : mamba env create -f requirements.yml
name: root_bridges
channels:
  - conda-forge
  - openalea3
dependencies:
  - python>=3.8
  # OpenAlea dependancies
  - openalea.plantgl
  - openalea.mtg
  - openalea.deploy
  - openalea.lpy
  - alinea.caribu
  - alinea.astk
  # data_utility dependancies
  - xarray
  - netcdf4
  - dask
  - charset-normalizer
  - bottleneck
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - umap-learn
  - hdbscan
  - imageio
  - imageio-ffmpeg
  - pyvista
  - openpyxl
  - cudatoolkit
  - tensorflow
  - statsmodels